# Generated by Django 5.2.9 on 2025-12-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_hz', models.BigIntegerField()),
                ('stop_hz', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
            ],
            options={
                'ordering': ['start_hz'],
            },
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('scanner_type', models.CharField(choices=[('pluto', 'ADALM-Pluto'), ('scpi-tti', 'TTi PSA Series'), ('scpi-owon', 'OWON XSA/HSA Series'), ('scpi-generic', 'Generic SCPI'), ('import', 'Imported Scan')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('online', models.BooleanField(default=False)),
                ('scanning', models.BooleanField(default=False)),
                ('current_band', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(choices=[('max', 'Max Hold'), ('min', 'Min Hold'), ('avg', 'Average')], max_length=10)),
                ('period_type', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily'), ('week', 'Weekly')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('hz_lo', models.BigIntegerField()),
                ('hz_hi', models.BigIntegerField()),
                ('step_hz', models.FloatField()),
                ('power', models.JSONField()),
                ('scan_count', models.IntegerField(default=0)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.band')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='core.scanner')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('scanner', 'band', 'aggregate_type', 'period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('hz_lo', models.BigIntegerField()),
                ('hz_hi', models.BigIntegerField()),
                ('step_hz', models.FloatField()),
                ('power', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.band')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.scanner')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['scanner', 'timestamp'], name='core_scan_scanner_dd8af7_idx'), models.Index(fields=['band', 'timestamp'], name='core_scan_band_id_7e08dd_idx')],
            },
        ),
    ]
