# Generated by Django 5.2.9 on 2025-12-11 00:13

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_band_per_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='auth_token',
            field=models.CharField(default=core.models.generate_auth_token, max_length=64),
        ),
        migrations.AddField(
            model_name='scanner',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Disabled scanners cannot connect'),
        ),
        migrations.AlterField(
            model_name='band',
            name='scanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='core.scanner'),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='scanner_type',
            field=models.CharField(choices=[('pluto', 'ADALM-Pluto'), ('scpi-tti', 'TTi PSA Series'), ('scpi-owon', 'OWON XSA/HSA Series'), ('scpi-generic', 'Generic SCPI'), ('import', 'Imported Scan')], default='pluto', max_length=20),
        ),
    ]
