# Generated by Django 5.2.9 on 2025-12-11 00:35

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_scanner_auth_token_scanner_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMQTTCredentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mqtt_credentials', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mqtt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auth_token', models.CharField(default=core.models.generate_auth_token, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User MQTT Credentials',
                'verbose_name_plural': 'User MQTT Credentials',
            },
        ),
    ]
