# Generated by Django 5.2.9 on 2025-12-14 20:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermqttcredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.generate_auth_token, max_length=64, unique=True)),
                ('label', models.CharField(help_text="Descriptive label (e.g., 'Super Bowl Demo')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive links are revoked')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['scanner', 'band', 'timestamp'], name='core_scan_scanner_f2f538_idx'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
