# Generated by Django 6.0.2 on 2026-02-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scannergroup_scanner_scanner_groups_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scanner',
            name='retention_policy',
            field=models.CharField(blank=True, default='', help_text='Graphite-style retention policy override (e.g. "1s:24h,1m:7d,5m:30d,1h:1y"). Empty = use global default.', max_length=200),
        ),
        migrations.CreateModel(
            name='ScanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('bucket_seconds', models.IntegerField()),
                ('hz_lo', models.BigIntegerField()),
                ('hz_hi', models.BigIntegerField()),
                ('step_hz', models.FloatField()),
                ('peak_power', models.JSONField()),
                ('avg_power', models.JSONField()),
                ('scan_count', models.IntegerField()),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.band')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_summaries', to='core.scanner')),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['scanner', 'bucket_start'], name='core_scansu_scanner_ac16d4_idx'), models.Index(fields=['scanner', 'band', 'bucket_start'], name='core_scansu_scanner_a28a5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('scanner', 'band', 'bucket_start', 'bucket_seconds'), name='unique_scan_summary_bucket')],
            },
        ),
    ]
