# Generated by Django 6.0.2 on 2026-02-24 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_scanner_retention_policy_scansummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scannergroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scanner Group', 'verbose_name_plural': 'Scanner Groups'},
        ),
        migrations.AlterModelOptions(
            name='scansummary',
            options={'ordering': ['-bucket_start'], 'verbose_name': 'Scan Summary', 'verbose_name_plural': 'Scan Summaries'},
        ),
        migrations.CreateModel(
            name='MonitoredFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency_hz', models.BigIntegerField(help_text='Exact frequency in Hz')),
                ('name', models.CharField(help_text='e.g. "Vox 1", "IEM Mix L"', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color (auto-assigned if empty)', max_length=20)),
                ('category', models.CharField(choices=[('Wireless Mics', 'Wireless Mics'), ('IEMs', 'IEMs'), ('Comms', 'Comms'), ('Intercom', 'Intercom'), ('WiFi', 'WiFi'), ('Other', 'Other')], default='Wireless Mics', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='monitored_frequencies', to='core.scannergroup')),
                ('scanners', models.ManyToManyField(blank=True, related_name='monitored_frequencies', to='core.scanner')),
            ],
            options={
                'verbose_name': 'Monitored Frequency',
                'verbose_name_plural': 'Monitored Frequencies',
                'ordering': ['frequency_hz'],
            },
        ),
    ]
