# Generated by Django 6.0.2 on 2026-07-31 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_alter_scannergroup_options_alter_scansummary_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='access',
            name='access_exactly_one_principal',
        ),
        migrations.AddField(
            model_name='access',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grant to every member of this Django group (e.g. SSO users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('token__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', True), ('token__isnull', False), ('user__isnull', True)), models.Q(('group__isnull', False), ('token__isnull', True), ('user__isnull', True)), _connector='OR'), name='access_exactly_one_principal'),
        ),
    ]
