// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function DetectDevice():Promise<string>;

export function DetectPluto():Promise<string>;

export function DetectTinySA():Promise<string>;

export function DisableMQTT():Promise<void>;

export function DisableWebServer():Promise<void>;

export function Disconnect():Promise<void>;

export function EnableMQTT():Promise<void>;

export function EnableWebServer():Promise<void>;

export function GetBands():Promise<Array<models.Band>>;

export function GetConfig():Promise<models.Config>;

export function GetConfigPath():Promise<string>;

export function GetDecimatedScans(arg1:string,arg2:number):Promise<Array<main.DecimatedScan>>;

export function GetGain():Promise<Record<string, any>>;

export function GetMQTTConfig():Promise<models.MQTTConfig>;

export function GetPlatform():Promise<string>;

export function GetScanAtTime(arg1:string,arg2:string):Promise<main.ScanEvent>;

export function GetScanStats():Promise<Record<string, any>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetStatus():Promise<main.StatusEvent>;

export function GetTimeline(arg1:string,arg2:number):Promise<Array<main.TimelineEntry>>;

export function GetWebConfig():Promise<models.WebConfig>;

export function SaveCSV(arg1:string,arg2:string):Promise<string>;

export function SaveConfig():Promise<void>;

export function SetBandEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetGain(arg1:number,arg2:string):Promise<void>;

export function SetMQTTConfig(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetWebConfig(arg1:boolean,arg2:number):Promise<void>;

export function StartScanning():Promise<void>;

export function StopScanning():Promise<void>;
