// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DetectDevice() {
  return window['go']['main']['App']['DetectDevice']();
}

export function DetectPluto() {
  return window['go']['main']['App']['DetectPluto']();
}

export function DetectTinySA() {
  return window['go']['main']['App']['DetectTinySA']();
}

export function DisableMQTT() {
  return window['go']['main']['App']['DisableMQTT']();
}

export function DisableWebServer() {
  return window['go']['main']['App']['DisableWebServer']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnableMQTT() {
  return window['go']['main']['App']['EnableMQTT']();
}

export function EnableWebServer() {
  return window['go']['main']['App']['EnableWebServer']();
}

export function GetBands() {
  return window['go']['main']['App']['GetBands']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetDecimatedScans(arg1, arg2) {
  return window['go']['main']['App']['GetDecimatedScans'](arg1, arg2);
}

export function GetGain() {
  return window['go']['main']['App']['GetGain']();
}

export function GetMQTTConfig() {
  return window['go']['main']['App']['GetMQTTConfig']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetScanAtTime(arg1, arg2) {
  return window['go']['main']['App']['GetScanAtTime'](arg1, arg2);
}

export function GetScanStats() {
  return window['go']['main']['App']['GetScanStats']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTimeline(arg1, arg2) {
  return window['go']['main']['App']['GetTimeline'](arg1, arg2);
}

export function GetWebConfig() {
  return window['go']['main']['App']['GetWebConfig']();
}

export function SaveCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveCSV'](arg1, arg2);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SetBandEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetBandEnabled'](arg1, arg2);
}

export function SetGain(arg1, arg2) {
  return window['go']['main']['App']['SetGain'](arg1, arg2);
}

export function SetMQTTConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetMQTTConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}

export function SetWebConfig(arg1, arg2) {
  return window['go']['main']['App']['SetWebConfig'](arg1, arg2);
}

export function StartScanning() {
  return window['go']['main']['App']['StartScanning']();
}

export function StopScanning() {
  return window['go']['main']['App']['StopScanning']();
}
